### PR TITLE
Add Korean Translation

### PR DESCRIPTION
**Pull request by mate131909**
The existing translation was machine translation.

And i found something strange during the work. Korean is divided into two categories: `ko` and `ko-KR`. Is this intended?

image

As a Korean, there seems to be no reason for these two to appear separately.
If it's not what was intended, it would be okay to remove one.

(I am not familiar with UWP development :( )

### CODE REVIEW

**Comment by mate131909** [comment]
I wish I could see the look the update is applied as soon as possible :)

**Review by Samuel12321 — CHANGES_REQUESTED** [review]
Hi @mate131909 this looks great, sorry it has taken some time, i have been quite busy at the moment.

The only question i have regarding your translations is why "flyout" is in English. Does no word exist in Korean for this, if not could it be substituted for a similar word?  

I was unable to replicate seeing 2 Korean languages in ModernFlyouts, which version were you using?

Thankyou so much for your help,
this will be included in the next release.

**Comment by mate131909** [comment]
**About 'Flyout'**

I had a lot of thoughts on how to translate 'Flyout'(Korean pronunciation is '플라이아웃').

The reason I didn't use '플라이아웃' is that it is also a word that only some developers can understand. There is no use of the term '플라이아웃' in Korea. In the case of word that are semantically similar, they are not appropriate because they have different connotation.

Therefore, the original text was used so that those who do not know the word 'Flyout' can just think of it as a proper noun used in ModernFlyouts.

Of course the difference between '플라이아웃' and 'Flyout' is subtle, but I thought 'Flyout' was a little better.

**2 Korean languages**

I'm using 0.9.0.0

If it's difficult to fix, don't have to worry. It does not affect the use.

---

I'm sorry for urging you.

Thanks for making a great program!

**Comment by Samuel12321** [comment]
Hi @mate131909 it may be best to use "플라이아웃" simply because otherwise people will make bug reports stating that there are parts not translated.
If you could change this, that would be great. I will merge this once that's done.

Thanks again for your help.

**Comment by mate131909** [comment]
I couldn't think about it.

@Samuel12321 Thanks for pointing out

**Review by Samuel12321 — APPROVED** [review]

**Pull request merged**
