### PR TITLE
Improve french translations

### PR DESCRIPTION
**Pull request by Arno500**
Some are pretty "unnatural" so I tried to make them a bit more readable 😄

### CODE REVIEW

**Comment by Samuel12321** [comment]
Hi @Arno500, Thanks so much for you help.

@Stealnoob can you review these translation updates.

My only concern was:
`          <target state="translated">Par défaut du système</target>`
          `<target state="translated">Système</target>`
According to google translate this would mean that the updated translation says system not system default?

**Comment by Arno500** [comment]
That's right. I wasn't sure about what I wrote, but "Par défaut du système" is quite long to read, and doesn't add a whole lot more infos than "Système" (Since there is context and we know that "System" is not a color scheme).
There is also the possibility of only using "Par défaut" ("Default") that doesn't say explicitly that it'll use the system-defined color scheme, but I don't necessarily think this is an important information (if the user already setup his system color scheme, then he'll be happy to see that's synced else he probably doesn't care what "Default" really means)

**Comment by ShankarBUS** [comment]
FYI,
The "System default" text is not only used for the theme selection radiobuttons, it is also used in the language selection combobox.

**Comment by Arno500** [comment]
> FYI,
> The "System default" text is not only used for the theme selection radiobuttons, it is also used in the language selection combobox.

I was not aware of that. I reverted that translation to allows it to be used multiple times 👍🏻

**Comment by ShankarBUS** [comment]
Merci! Merci beaucoup @Arno500!

@Samuel12321 FYI.

**Comment by Stealnoob** [comment]
Kinda late to the party, but approving the changes

**Review by Samuel12321 — APPROVED** [review]
looks good thanks

**Review by thomasbnt — COMMENTED** [review]
Hello! 
~~I'm french and I approve this PR. Trad seems correct!~~

Aaah, it's already merged. I see that after commenting. Sorry for this bad notification 😆

**Pull request merged**
