### PR TITLE
Polish Patch

### PR DESCRIPTION
**Pull request by Cyberdroid1**

### CODE REVIEW

**Comment by Cyberdroid1** [comment]
dont merge it. i will do on my own

**Comment by Samuel12321** [comment]
why is it marked polish update, there are no changes to polish translations?

**Comment by Cyberdroid1** [comment]
> why is it marked polish update, there are no changes to polish translations?

I am "polishing" the readme, thats why the name. 

Even Discord made an update and named it "Polish Patch" :D

**Comment by Samuel12321** [comment]
oh right my mistake, i thought you meant polish as in the language 😉

**Comment by ShankarBUS** [comment]
@Cyberdroid1 bruh

**Comment by Cyberdroid1** [comment]
Lets add screenshots with this pull request, shall we?

**Comment by Cyberdroid1** [comment]
How about fixing #58 with this PR? Since the content is similar anyway

**Comment by Samuel12321** [comment]
We can certainly look into options for the store page, however the store images need to be high res preferably vector images.

**Comment by Cyberdroid1** [comment]
Please see and give feedback on usage of emojis.

**Comment by Samuel12321** [comment]
Perhaps change the contributors / translators list to a link to https://github.com/ModernFlyouts-Community/ModernFlyouts/graphs/contributors
to shorten readme page

**Comment by Cyberdroid1** [comment]
Sounds good!

How about removing the whole section altogether? The main page shows the contributors list anyway
image

@ShankarBUS give views

**Comment by Samuel12321** [comment]
i still think we should have a brief thing saying thanks ... with a link.

**Comment by Cyberdroid1** [comment]
I just had a big-brain idea. How about we create a text file in the repo named "Contributors.md" which will contain this stuff.

**Comment by Samuel12321** [comment]
isn't it a bit redundant, plus means we have to maintain it - the GitHub contributors page updates automatically

**Comment by Cyberdroid1** [comment]
Hm, good point. Will do what you said, adding a link.

**Comment by Cyberdroid1** [comment]
@Samuel12321 does this look fine?

**Review by Samuel12321 — APPROVED** [review]
looks good, however i probably wouldn't say most importantly localisation as all contributions are helpful

**Comment by Cyberdroid1** [comment]
> looks good, however i probably wouldn't say most importantly localisation as all contributions are helpful

well, most of our contributions are mainly localisation lol. 

will edit it accordingly.

**Comment by Samuel12321** [comment]
@Cyberdroid1 what's the plan for merging this?

Only changes that need to be made are "most importantly localisation" and the chocolatey stuff should be below winget as we should prioritise supported distributions.

**Comment by Cyberdroid1** [comment]
I will make the changes you said.

I need to make screenshots too, just trying to find some time to make those 😅

**Pull request merged**
