### PR TITLE
Pull request for battery flyout (0.10)

### PR DESCRIPTION
**Pull request by FireCubeStudios**
This initial request adds, assets, dll, usercontrol with battery flyout UI and an empty settings page. We still need to figure out how to save the json data, create a tray icon flyout and manage it.

### CODE REVIEW

**Comment by FireCubeStudios** [comment]
Also i guess change the UI too

**Comment by Samuel12321** [comment]
@FireCubeStudios, do you want merge permissions so you can work on the 0.10 branch without having to open new PR's?

**Comment by FireCubeStudios** [comment]
> @FireCubeStudios, do you want merge permissions so you can work on the 0.10 branch without having to open new PR's?

sure

**Comment by FireCubeStudios** [comment]
found a bug where the battery dll has some errors showing. i will try to fix that

**Pull request merged**
