### PR TITLE
Add Chinese Traditional Translation

### PR DESCRIPTION
**Pull request by TragicLifeHu**
Initial release
Optimized for Taiwan Region.

### CODE REVIEW

**Comment by Samuel12321** [comment]
Hi, thanks so much for your help.
Just waiting to see what happens with #250 before merging this.

**Review by Samuel12321 — COMMENTED** [review]
Hi @TragicLifeHu,
Thanks so much for your help, sorry for the delay have been waiting on #250. 
Would you wind merging this into just a single zh-hant, (it can be optimised for 
Taiwan).

**Comment by TragicLifeHu** [comment]
> Hi @TragicLifeHu,
> Thanks so much for your help, sorry for the delay have been waiting on #250.
> Would you wind merging this into just a single zh-hant, (it can be optimised for
> Taiwan).

I don't mind, just merge it is OK.

**Comment by Samuel12321** [comment]
@ShankarBUS should i merge this? it seems that we are leaning towards zh-CN and zh-TW with remap any further thoughts?

**Comment by ShankarBUS** [comment]
Yeah merge it.

**Pull request closed without merging**
