### PR TITLE
Flyout animation toggle

### PR DESCRIPTION
**Pull request by karpovv-boris**
1. Added toggle for disabling Flyout animation.
2. Russian translation updated.

### CODE REVIEW

**Comment by karpovv-boris** [comment]
Result:
result

**Comment by karpovv-boris** [comment]
It also was mention about performance. 
Find this how-to:
https://docs.microsoft.com/en-us/dotnet/desktop/wpf/graphics-multimedia/how-to-improve-rendering-performance-by-caching-an-element?view=netframeworkdesktop-4.8

Not sure maybe it should be like this:
cache mode

And don't know how to measure it, although I haven't tried benchmark-dotnet

**Comment by Samuel12321** [comment]
Thanks so much for your help @karpovv-boris , this has been added to the 0.9.2 release. 
Will just get @ADeltaX or @ShankarBUS to review before merging.

**Comment by karpovv-boris** [comment]
Glad to help.

**Comment by karpovv-boris** [comment]
Please, use russian translation from this PR https://github.com/ModernFlyouts-Community/ModernFlyouts/pull/510

**Review by ADeltaX — APPROVED** [review]

**Comment by Samuel12321** [comment]
Merged, Thankyou @karpovv-boris , this will be visible in 0.9.2

**Comment by oacoello** [comment]
Thank you for adding the animation toogle

**Comment by karpovv-boris** [comment]
@oacoello you're welcome

**Pull request merged**
