### PR TITLE
Samtesting01

### PR DESCRIPTION
**Pull request by Samuel12321**
- Added new navigation sub-header for flyout position as additions to these controls are upcoming
- Modified appinstaller package
- Started modification of app update control

Not ready to be merged yet. The Navigation view sub header for flyout position needs approval and isn't working yet. Not sure why, however doesn't seem to be bound to the new page correctly.

### CODE REVIEW

**Comment by ShankarBUS** [comment]
Hmm.

I had a different idea on my mind.

Like using **"Layout"** instead of **"Flyout Position"**.

Layout would suit much better, wouldn't it?

**Comment by Samuel12321** [comment]
possibly best to ask the community on this one, i just thought "flyout Position" was very clear and precise. Where as layout doesn't specify what layout is being changed.
Just my thoughts.

**Comment by ShankarBUS** [comment]
Layout would be better than Flyout Position.

 Because, the page would also include a monitor control, expand direction and etc.

Anything but Flyout Position is ok for me.

**Comment by Samuel12321** [comment]
ok layout it is

**Pull request closed without merging**
