### PR TITLE
feat: click session-control bg to close it

### LINKED ISSUE #415: Feature Request: Click an empty space to hide the flyout
**Is your feature request related to a problem? Please describe:**
I have my flyout set to appear in the center of the screen, sometimes when I am working or doing something I increase the volume or play the next song which triggers the flyout but I have to wait for the 2000ms duration to end before I can get back to what I am doing which gets kinda annoying sometimes.

**Describe the solution you'd like:**

if you click on an empty space in Windows 10 default flyout, it just hides it instantly which I think ModernFlyouts should implement.

**Describe alternatives you've considered:**

**Additional context:**

### PR DESCRIPTION
**Pull request by amrbashir**
Closes #415 

I am not a WPF developer and I am shooting in the dark here, so bear with me.

<s>This PR does close the flyout when clicking an empty space on the thumbnail but if the thumbnail option is turned of, it won't work and If I understand correctly, that's because of `BooleanToVisibilityConverter` which converts `false` to `Collapsed` and not `Hidden`.</s>

<s>I tried to add a new empty `Border` after the thumbnail but it didn't work, I don't know why (poor wpf skills 😅).</s> Just needed to give it a Background color lol.

<s>The other thing that might work (haven't tested it), is to make a custom `BooleanToVisibilityConverter` which converts `false` to `Hidden` but that seemed overkill imo.</s> Won't work as `Hidden` will make all clicks go through.

### CODE REVIEW

**Comment by ShankarBUS** [comment]
I'll review this PR. Please be patient.

**Comment by amrbashir** [comment]
No hurry, it is not urgent.

**Comment by Samuel12321** [comment]
This would need to be a setting as some people wouldn't want the flyout to instantly disappear if they are using their mouse.

**Comment by Samuel12321** [comment]
Sorry just looked closer at the pr, - so you want to close the flyout if the user clicks on the flyout?
Isn't that a bit of a contradictory command?

**Comment by amrbashir** [comment]
> Sorry just looked closer at the pr, - so you want to close the flyout if the user clicks on the flyout?
> Isn't that a bit of a contradictory command?
Only if the click was on the background not buttons.

As I explained in the linked issue, sometimes the flyout can be intrusive and needed to be closed immediately, and that's how the default win10 flyout works anyway.

If it needs to be a setting, I am fine with that.

**Comment by Samuel12321** [comment]
Yes it will need to be a setting, but i guess another feature is never a bad thing.

**Comment by amrbashir** [comment]
I finally figured out why the empty `Border` wasn't working (just needed a Background) and added a setting for it.

**Comment by amrbashir** [comment]
I hate to ask, but is there any ETA on when this might get merged ?

**Comment by Samuel12321** [comment]
Hi @amrbashir , sorry for the delay. It irritates me immensely that you had to ask. I said I would never let prs just sit unmerged like some repo's do. However unfortunately we are having some trouble progressing with the next release, the original team is either busy, or unable to code at the moment like @ShankarBUS, and no one from the community has stepped up to help. We have just recruited @FireCubeStudios so hopefully we will start getting some movement soon.
Additionally Microsoft's not making it easy for us with problems preventing us migrating to winui3 or islands.

So to answer your original question, honestly im not sure but as soon as we can. Apologies again for the delay.

**Comment by amrbashir** [comment]
Maintaining an open source project is no easy task and I totally understand. You guys did a good job with the project, take care of yourselves.

**Comment by ShankarBUS** [comment]
So,..... Ummmm..... @amrbashir, I fixed this issue myself and forgot this PR exists 😅. Sorry for forgetting this PR.
I am really worried that I couldn't merge this PR 😥.

Thanks for contributing. We will surely accept your future contributions 😄.

**Comment by Samuel12321** [comment]
This will be in the next update

**Comment by amrbashir** [comment]
> So,..... Ummmm..... @amrbashir, I fixed this issue myself and forgot this PR exists 😅. Sorry for forgetting this PR.
> I am really worried that I couldn't merge this PR 😥.
> 
> Thanks for contributing. We will surely accept your future contributions 😄.

No worries, the important thing is the feature is done.



> This will be in the next update

Thanks

**Pull request closed without merging**
