### PR TITLE
Make volume changing behaviour consistent with OS

### PR DESCRIPTION
**Pull request by krlvm**
Before, when you set volume to 0 in flyout, it did not become muted.
When the audio was muted, it was impossible to adjust volume.

Now that the volume is set to 0, it also mutes can be unmuted by setting the volume to greater than 0, so it is consistent with system volume flyout behaviour.

https://user-images.githubusercontent.com/51774833/119239345-1ee4fa80-bb51-11eb-97fe-b8241cdc775a.mp4

### CODE REVIEW

**Comment by ShankarBUS** [comment]
TBH, this is what I wanted to do for a long time. But, in #23, @Cyberdroid1 and @Samuel12321 suggested the idea to disable the sliders (that will make it grey) inorder to denote the muted state visually.

There was no complaints to change this behavior since then.
That's why I didn't bother about it afterwards.

This PR can be merged. 👍🤌

**Comment by krlvm** [comment]
I'd like to make the slider gray, but I haven't found the way to do that :(

**Comment by ShankarBUS** [comment]
I will try to do that once this PR has been merged 😄

**Comment by ShankarBUS** [comment]
Why this PR targetting main? Hey fella, can you retarget it to the dev branch?

**Comment by krlvm** [comment]
Oh, didn't notice

**Pull request closed without merging**
