### PR TITLE
Option for hiding media playback timeline

### LINKED ISSUE #392: Feature Request: Hide Timeline bar when not supported by media app
If there is an option that allows the user to hide the progress bar by default in modern flyout, there will be less space consumed, and it will make the whole application looks better

### PR DESCRIPTION
**Pull request by krlvm**
Details in #628
Close #392

### CODE REVIEW

**Comment by Samuel12321** [comment]
Hi @krlvm, thanks so much for your help, will try to get these merged soon so they are part of the next release

**Comment by ShankarBUS** [comment]
@krlvm, thanks for your effort.

But, unfortunately I hardcoded the Design and Layout.

What your PR does is, it provides an option to completely hide the seekbar whether or not it is supported.

But I hard-coded the height of the control to accommodate the seekbar. If you hide the seekbar, the height will change and there will be issues in scolling the session controls.

And hiding the seekbar also for all supported sessions inorder to hide it for unsupported sessions is not a good workaround in my opinion.

Unfortunately, I can't accept this PR 😔.

Thanks for your efforts again

**Comment by krlvm** [comment]
Thanks for review, but can we change the hardcoded height depending on this option?

**Comment by ShankarBUS** [comment]
@krlvm,

> but can we change the hardcoded height depending on this option?

I have a different plan, like bringing up the slider on hover or click only for supported apps. Other sessions won't have this normally. Only those which support time-line will have a progress bar on the bottom and on hover or click, it will pop out as a slider.

So, I myself will take care of this 😉. Because it is too much work.

> I know that hiding it for supported apps is not good, but as user I wouldn't notice that because no app I use supports this functionality and I do not mind completely disabling it.

Yep, most apps don't bother about this feature, because Windows doesn't make use of the time-line feature yet. As I said, I will make a UX revamp later this month. I will do this thing together with that.

> BTW, what do you think about showing volume & media control on tray icon single click until Windows get media control in volume flyout?

Yeah, we have this planned. There is a feature request for this. We couldn't do this due to the lack of our free time and I have a crappy old laptop which is pretty unusable at this point of time.

I will do my best 😄. Thanks again for your contribution and enthusiasm!!! ❤💖

**Pull request closed without merging**
