### PR TITLE
Update Chinese Traditional Translation

### PR DESCRIPTION
**Pull request by TragicLifeHu**
I don't know how to edit a PR, so I renewed it there

### CODE REVIEW

**Comment by Samuel12321** [comment]
hi @TragicLifeHu sorry this has taken so long to sort out.
Going forward we are going to simplify it to just zh-cn and zh-tw, would you mind changing it to this?
Apologies again, as soon as i get the updated translations from you i will merge them

**Comment by TragicLifeHu** [comment]
That is OK. Feel free to merge them

**Comment by Samuel12321** [comment]
can you change the names to zh-cn and zh-tw ?

**Comment by TragicLifeHu** [comment]
I directly edited the file on GitHub Website, so you have to change it manually. Sorry for the inconveniences

**Review by Samuel12321 — APPROVED** [review]
Looks great thanks

**Pull request merged**
