### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by erayrafet**

### CODE REVIEW

**Comment by ShankarBUS** [comment]
@Cyberdroid1, merge this bro

**Comment by Cyberdroid1** [comment]
While I agree with Win10 change, I don't like the other changes.
We need to keep it similar to the website, I think.

**Comment by ShankarBUS** [comment]
That's the same as in our website

**Comment by erayrafet** [comment]
https://github.com/ModernFlyouts-Community/ModernFlyouts-Community.github.io/pull/8

**Comment by Cyberdroid1** [comment]
Oh ok, my bad.

**Comment by Cyberdroid1** [comment]
MERGING

**Pull request merged**
