### PR TITLE
Updated Greek Translation

### PR DESCRIPTION
**Pull request by VasilisPat**
Some translated messages don't fit inside the flyout notification box.

Στιγμιότυπο οθόνης (47)

### CODE REVIEW

**Comment by Cyberdroid1** [comment]
@Samuel12321

**Comment by Samuel12321** [comment]
@VasilisPat Which translations don't fit in the flyout?

**Review by Samuel12321 — APPROVED** [review]

**Comment by VasilisPat** [comment]
@Samuel12321 As far as I have noticed, the only translation affected is the num lock option. I am trying to find a shorter phrase with the same meaning to change the translation, in order to avoid margin overrun.

**Comment by Samuel12321** [comment]
@VasilisPat would "αριθμός κλειδώματος" work (courtesy of google translate)

**Comment by VasilisPat** [comment]
No it doesn't match with the actual meaning of the phrase (although close enough, well done google translate :) ). I will change it just to num lock on & off. If anyone sees that message they know which button they are pressing. The simpler the better.

**Comment by Samuel12321** [comment]
do people use "num lock" in greek?

My concern is just that people will complain and say it wasn't translated unless this is common practice in Greece

**Comment by VasilisPat** [comment]
There is no actual translation for num lock, just some phrases with similar meaning. Also there is no one who presses this button and doesn't know what num lock does/mean. I suggest leaving it as is for now and in the future if the flyout gets automatically resized to action's text, I will revert its translation to the full phrase.

**Review by Samuel12321 — APPROVED** [review]

**Comment by Samuel12321** [comment]
Thanks @VasilisPat , this should be visible in 0.9.2

**Pull request merged**
