### PR TITLE
v0.9

### LINKED ISSUE #29: Bug: Media Sessions are not updating in Windows 10 2004
**Description of the bug :**

Starting from Windows 10 2004 the **GlobalSystemMediaTransportControlsSessionManager** is broken and the `GlobalSystemMediaTransportControlsSessionManager.SessionsChanged` event is not firing properly.

Meaning that the session controls won't be upated whenever an app opens/closes (e.g. Test yourself with Groove Music) & etc.
This makes the session controls (which is a very important feature of this app) useless. But the built-in flyout works somehow.

Source :
Manual verification and from our collaborator @ADeltaX (in https://github.com/ADeltaX/AudioFlyout/issues/12)

> Also I heard that GSMTC as WinRT api is broken in 19041.x (doesn't get notified when an app closes SMTC (e.g. when you close Groove Music))

**Current Workaround :**

Restarting the app updates the sessions (won't update again we have to restart again to update).

**Expected behaviour :**

The app updates itself whenever the GSMTC sessions are updated.

**Proposed method :**

If can't provide any programmatic fix, at-least provide an update button to refresh them manually. Instead of forcing users to restart the app and making things complex.

### LINKED ISSUE #32: Bug: ModernFlyouts gets hidden behind other topmost windows and not shown in Lockscreen
@TharukaN97,

When i use volume up/down , Brightness up/down when watching video in Fullscreen or While playing a game in Fullscreen, Modern Flyouts overlay not appearing top of full screen video / game.

@Sebastian1896,

When the Start Menu is present the flyout gets lost behind. The windows default one is always on top in any moment.

@validatedev,

I cannot see any popup for brightness, caps lock, etc. while the Windows lock screen is activated.

### LINKED ISSUE #69: Support for DPI Awareness
#68

### LINKED ISSUE #71: Feature Request: Add the ability to change whether the Media controls appears below or above the Volume controls and and the ability to control the expand direction
@Samuel12321:

In 0.5 we added the ability to change where on the screen the flyout appeared, however if the user moves the flyout to the bottom of the screen, the media flyout can go off the screen.

@jean3x7:

I want to dock the flyout to the bottom without the content being hidden

Current behaviour:
image
image

Proposed behaviour:
image
image

### LINKED ISSUE #74: Feature Request: Offer some sensible default positions
It would be nice if the user could choose top/bottom and left/center/right, all with some padding to the borders. Moving it manually is not as pixel-perfect as just saying "center top".

For bottom positions, the expansion direction would have to be upwards.

### LINKED ISSUE #97: Feature proposal: Add support for seeking or changing the progress of the media playback
from @Samkunmiayo's request
**Is your feature request related to a problem? Please describe:**

Amazing app! Would be amazing to have the ability to seek the current audio in the timeline info section.

**Describe the solution you'd like:**

Addition of a seek feature similar to the volume slider to enable the user go to a certain section of the song or podcast, like in spotify for example

**Describe alternatives you've considered:**

**Additional context:**

image

### LINKED ISSUE #114: Timeline info suggestion
> The Time Line info bar should always show in panel, instead of click button to see the progress!

Store review, perhaps this could be a toggle setting

### LINKED ISSUE #135: Feature Request: On Computers with multiple monitors, have a setting to change which monitor the flyout appears on.
While this can be done by dragging the flyout to the second monitor, an option or toggle to set which monitor it appears on would be nice.

### LINKED ISSUE #136: Feature Request: Split the Media session Flyouts and volume flyouts as it was pre 0.5
I have talked with @ShankarBUS about this, but thought i would create a proper request for it.

- Aligns more with windows 10X and feels more modern in my opinion

### LINKED ISSUE #183: Feature Request: Move flyout default position setting to personalisation page from general
poor guy is all alone :(
image

ModernFlyouts version: 0.8.0.1
Windows 10 version: 20H2

### LINKED ISSUE #184: Bug: Win32 apps' information are not shown in the media session controls
**OS Version:**
 - Windows 10 Version: 20H2

**ModernFlyouts Version:**
 - Version: 0.8.0.1

**Additional context:**

### LINKED ISSUE #224: Feature Request: Option to toggle the album art background for media controls
Store feedback.

> "An excellent app that should be built into Windows 10. The updated design is fantastic and it works flawlessly! Possible ideas for improvement: - Allow the media controls to expand the volume control upwards. Right now you can't align the volume control to the bottom of the screen because when it expands to account for media, it ends up below the taskbar. This forces the user to pin the volume control near the top of the desktop (e.g. the default position). - An option to toggle the album art background when enabling media controls."

### LINKED ISSUE #305: Bug: Pressing and holding caps lock toggles flyout twice.
**Describe the bug:**

**To Reproduce:**

1. Press and hold CAPS LOCK.
2. Notice how the correct flyout is displayed at first. 
3. Notice how the flyout toggles again to the incorrect icon and message.

**Screenshots:**

**OS Version:**
 - Windows 10 Version:  2004

**ModernFlyouts Version:**
 - Version:  0.8.4 (as shown in Windows settings)

**Additional context:**

After pressing CAPS LOCK a second time, it displays the correct icon. It only shows the incorrect flyout when holding. 
My flyout delay is set to 500ms.

### LINKED ISSUE #312: Bug: Use mousewheel turn up volume will stuck at some value
**Describe the bug:**

Use mousewheel to turn up the volume, it will stuck at some value. Turning down is as normal.

On my laptop it will stuck at 1 3 12 15 24 26 53 59, unless I use keyboard or mouse dragging to turn up across these value.

I don't know this is a common problem or just incompatible with some specific device.

**To Reproduce:**

1. Active the flyouts

2. Try to use mousewheel turn up volume

**OS Version:**
 - Windows 10 Version: 20H2 Build19042.685 

**ModernFlyouts Version:**
 - Version: 0.8.5.0 

**Device Model:**

 - Lenovo IdeaPad S540-13IML (i7-10710U)

### LINKED ISSUE #327: Feature request: Multi-monitor support
Hope there can be a Multi-monitor support that allows user to configure modern flyout on extended displays on Windows 10.

### LINKED ISSUE #361: Feature Request: media background thumbnail modes [stretch, fit or fill]
**Is your feature request related to a problem? Please describe:**

The background thumbnail is not consistent, some thumbnails are big which covers the whole flyout but others don't which irritates me to be honest (symmertical ocd).

**Describe the solution you'd like:**

A new dropdown menu option where I can select one of three modes, stretch, fill, or fit.

Love your app though and appreciate your work.

### PR DESCRIPTION
**Pull request by ShankarBUS**
🎉🎉🎉🎉🎉🎉🎉🎉🎉🎊🥳🥳🥳🎊🎉🎉🎉🎉🎉🎉🎉🎉🎉

This PR contains a whole month's work. It introduces several new features and many bug fixes!

# Release Notes

### Bug Fixes

- Fixed #29 - **Bug: Media Sessions are not updating in Windows 10 2004**. This bug is caused by an issue in a Windows 10 WinRT API called `GlobalSystemMediaTransportControlsSessionManager`. Its `SessionsChanged` event didn't get raised since Windows 10 2004 which they fixed in a later insider build. A huge thanks to @ADeltaX!

- Fixed #32 - **Bug: ModernFlyouts gets hidden behind other topmost windows and not shown in Lockscreen**. This issue happens due to the restrictions laid down by Windows. Windows doesn't allow regular top-most top-level windows to be shown on top of several other windows (some full-screen apps, Start menu, Always-On-Top Task Manager and the lock screen). We had to do some dark magic to get this thing to show on-top of every window which the native flyout could. Thanks to @ADeltaX for discovering the [CreateWindowInBand](https://blog.adeltax.com/window-z-order-in-windows-10/) private API and for getting the dll injection to work properly.

- Fixed #184 - **Bug: Win32 apps' information are not shown in the media session controls**. Another issue caused by the Windows 10 WinRT API `GlobalSystemMediaTransportControlsSessionManager`.

- Fixed #305 - **Bug: Pressing and holding caps lock toggles flyout twice.**. Fixed as a part of #306 by a community member @Renzo904. Thank you @Renzo904! ❤❤❤

- Fixed #312 - **Bug: Use mousewheel turn up volume will stuck at some value**. Fixed as a part of #313. Thanks again @Renzo904!

### What's New

- Resolved #327 - **Feature request: Multi-monitor support**. Now, you can select which monitor the flyout auto align to or be moved to (based on relative position).

- Resolved #74 - **Feature Request: Offer some sensible default positions**. From now on, there are options to auto place the flyout to your desired alignment on your desired monitor.

- Resolved #71 - **Feature Request: Add the ability to change whether the Media controls appears below or above the Volume controls and and the ability to control the expand direction**. Two new options called **"Content stacking direction"** and **"Expand direction"** (expand animation direction, to be precise) have been added.

- Resolved #135 - **Feature Request: On Computers with multiple monitors, have a setting to change which monitor the flyout appears on**. Related to #327.

- Resolved #136 - **Feature Request: Split the Media session Flyouts and volume flyouts as it was pre 0.5**

- Resolved #97 - **Feature proposal: Add support for seeking or changing the progress of the media playback**. The timeline info progress bar has now been replaced by a slider. This change allows you to seek the playback position easily from ModernFlyouts without having to open the source application.

- Resolved #114 - **Timeline info suggestion**. The timeline info controls have been moved into the main flyout instead of being in a separate flyout.

- Resolved #224 - **Feature Request: Option to toggle the album art background for media controls**. Fixed as a part of #315 by another community member @fheck. Thanks to you too @fheck! ❤❤❤.

- Resolved #183 - **Feature Request: Move flyout default position setting to personalisation page from general**

- Resolved #69 (noice) - **Support for DPI Awareness**

- Resolved #361 - Fixed an issue where Spotify's thumbnail were scaled improperly. We had to crop the extra padding and their branding from the thumbnails provided by Spotify. 

- Reworked topbar animations.

### Known issues

- Tooltips gets hidden behind the main flyout. **I know!** I worked 3 weeks with this! I **AM** fully aware of this

- Flyout **bounces indefinitely** (lol XD XD hilarious) on hover sometimes when the topbar is set to auto-hide and the flyout is auto aligned to bottom.

- Users can't specify how close the flyout can get to the screen bounds (or can't set margin, to be precise) when it's auto placed. The ability has already been added internally but due to time limitations this feature couldn't make it to this release.

#### NowPlayingSessionManager

**INowPlayingSessionManager** (INPSM) is a private Windows 10 API (since 1511) which is also the core API used by the native flyout and a Windows 10 WinRT API called **GSMTC** ([GlobalSystemMediaTransportControlsSessionManager](https://docs.microsoft.com/en-us/uwp/api/windows.media.control.globalsystemmediatransportcontrolssessionmanager)) (since Windows 10 1809). We were previously using **GSMTC** for our media controls. But it lead to some dead ends like #29 & #184. In order to overcome the issues laid down by the **GSMTC** APIs, @ADeltaX suggested to use a private API found in Windows 10 reserved for internal usage called **INowPlayingSessionManager**. But there were plenty of problems while doing so. Since **INPSM** is reserved for internal usage by Microsoft, they didn't care about breaking and altering it in every Windows 10 build.

@ADeltaX had to do all the hard work to get it running across all Windows 10 versions properly.
He wrote a wrapper called **NPSMLib** which will execute OS specific functions and work on all Windows 10 versions from 1511 to the latest insider builds.
He made a standalone [Nuget package called NPSMLib](https://www.nuget.org/packages/NPSMLib) so that others could be benefited too.

If you're interested in the **NPSMLib**, please check out its [GitHub repository](https://github.com/ADeltaX/NPSMLib).

#### Above Lockscreen & Topmost Flyout

Some users were struggling with the flyout getting hidden behind some full-screen apps, Start Menu, Always-on-top Task Manager & the lock screen. While the native flyout had no problems with being topmost, we had no options other than doing some black magic.

@ADeltaX [discovered and documented a private Windows API](https://blog.adeltax.com/window-z-order-in-windows-10/) called **`CreateWindowInBand`** which he made use of in his [AudioFlyout](https://github.com/ADeltaX/AudioFlyout) and [MobileShell](https://github.com/ADeltaX/MobileShell).

This **CreateWindowInBand** API is also reserved for internal usage by Microsoft and has plenty of restrictions in order to prevent it from being used by 3rd party applications. The **CreateWindowInBand** works fine if we target the normal window band but for higher bands MS has laid some serious restrictions.

> CreateWindowInBand/Ex **works ONLY if you pass ZBID_DEFAULT or ZBID_DESKTOP** as dwBand argument. Also **ZBID_UIACCESS is permitted only if the process has UIAccess token** (obtainable, for example, by setting `uiAccess=true` in `app.manifest`, more info [here](https://docs.microsoft.com/en-us/windows/win32/winauto/uiauto-securityoverview)). **Any other ZBID will fail with 0x5 (ACCESS DENIED)**.

> For CreateWindowInBand/Ex, to be able to use more ZBIDs, the program must have a special PE header, named **".imrsiv"** ( bss_seg), flagged with **IMAGE_DLLCHARACTERISTICS_FORCE_INTEGRITY** and be **signed with a Microsoft certificate "Microsoft Windows"**.

*Quoted from ADeltaX's blog*

So, in order to use the **CreateWindowInBand** API, we need the executable to be either
- an **UIAccess** enabled process which indeed requires it to be **signed by a proper certificate** (could be obtained but costs a lump amount of money).
- an **immersive process** and be **signed with a Microsoft certificate "Microsoft Windows"**.

Both of them won't happen obviously. This is where the ***black magic*** kicks in.

So, what we need is a **surrogate host** which has the ability to be an **immersive process** and be **signed with a Microsoft certificate "Microsoft Windows"** and won't do anything other than hosting our application. And guess what? @ADeltaX strikes again! He discovered the proper host for this purpose which is called as the **"RuntimeBroker"** (an immersive, MS signed surrogate application found inside `C:\Windows\System32\`). He had to get 4 architecture specific **RuntimeBroker** executables from 4 different Windows 10 OSes (x86, x64, ARM and ARM64). He renamed it to **`Bro_(arch).exe`** for fun.

Using **RuntimeBroker** to host and execute our application was not a joke. It required us to do ***dll injection*** and host the .NET 5 **CoreCLR** inside of it. For further information see this comment - https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/32#issuecomment-735454172.

I can assure you this procedure is completely safe and secure. It won't affect your system and infringe your privacy. We guarantee you on that.

Somehow, we made it to work properly. We can't thank @ADeltaX enough for all his help ❤. Attributing him is the only thing we can do in return.

#### Final Words

I @ShankarBUS, the **author** and **lead developer** of this project will be leaving this team and this project in the hands of the other 3 core team members @Samuel12321, @Cyberdroid1 and @ADeltaX.

This will be the last release from myside.

Before leaving, I would like to give huge shout-outs to
- @ADeltaX, for [AudioFlyout](https://github.com/ADeltaX/AudioFlyout) and every single help from him.
- @Samuel12321 (co-owner, publisher and maintainer), for publishing this application to Microsoft Store, WinGet, dealing with users and helping me maintain this repo since its early stages.
- @Cyberdroid1, for his ideas, suggestions, motivation, help and enthusiasm for this project.
- And finally all the community members (either on Discord, Telegram or GitHub), for all the contributions, motivations, suggestions, ideas and help and everything!

It means a lot to me.

My final words: ***Change da world… my final message. Goodb ye***.

### CODE REVIEW

**Comment by ShankarBUS** [comment]
@Samuel12321,

I need you to verify whether everything is alright. After that **I'll merge this PR** (please let me do it for one last time)

**Comment by Cyberdroid1** [comment]
Lmao the # number of the PR. Very nice indeed.

@ShankarBUS, You will be missed... ❤

**Comment by Samuel12321** [comment]
@ShankarBUS of course.
Starting to review it now.
what happened to #250 ?

**Comment by ShankarBUS** [comment]
Ummmmmm

**Comment by ShankarBUS** [comment]
Meow?

**Comment by ShankarBUS** [comment]
@Samuel12321,

Merge this normally with a merge commit.

**DO NOT** SQUASH OR REBASE MERGE!

# JUST NORMAL MERGE WITH A MERGE COMMIT.

I'll be asleep in a while.

Hit me up after releasing v0.9 to Store.

**Comment by Tropix126** [comment]
git moment

**Pull request merged**
